CREATE ROLE "diabetyk-user" LOGIN
ENCRYPTED PASSWORD 'md59dd9ea69cdb9c89d1036a5b245293d3f'
NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;

CREATE DATABASE diabetyk
WITH OWNER = "diabetyk-user"
ENCODING = 'UTF8'
TABLESPACE = pg_default
LC_COLLATE = 'pl_PL.UTF-8'
LC_CTYPE = 'pl_PL.UTF-8'
CONNECTION LIMIT = -1;
